[Workflow] Trying to capture an error message
Signed-off-by: Phillip Rak <rak.phillip@gmail.com>

diff --git a/.github/workflows/port-pr.yaml b/.github/workflows/port-pr.yaml
--- a/.github/workflows/port-pr.yaml
+++ b/.github/workflows/port-pr.yaml
@@ -81,8 +81,10 @@ jobs:
           git config --global user.name "Rancher Dashboard Port Bot"
           git checkout -b $BRANCH
 
-          if ! git am -3 "$PATCH_FILE"; then
-              gh issue comment ${ORIGINAL_ISSUE_NUMBER} --body "Not creating port PR, there was an error running git am -3"
+          if ! git am -3 "$PATCH_FILE" 2>error.log; then
+              ERROR_MESSAGE=$(< error.log)
+              FORMATTED_ERROR_MESSAGE=$(printf "\n```\n%s\n```" "$ERROR_MESSAGE")
+              gh issue comment ${ORIGINAL_ISSUE_NUMBER} --body "Not creating port PR, there was an error running git am -3: $FORMATTED_ERROR_MESSAGE"
           else
               git push origin $BRANCH
               ORIGINAL_PR=$(gh pr view ${ORIGINAL_ISSUE_NUMBER} --json title,body,assignees)
